### ISSUE TITLE
Improve the "Vanila Theme": font and display issues for compatibility with Pd-Vanilla

### ISSUE THREAD

**Issue by porres** [timothyschoen/PlugData#1882]
this is a reboot of https://github.com/plugdata-team/plugdata/issues/1656

First I'd like to ask for 
- [ ] A theme named 'vanilla' instead of classic 

Now for some display and font issues. You see, a Vanilla theme would require the 'Menlo' font, and also the fact that setting the font in the settings should affect comments, objects and all text in a patch. We can set the 'Menlo' font alright, but it doesn't affect the patch. So we need to 

- [ ] make the font theme set text in a patch (old discussion in 
https://github.com/plugdata-team/plugdata/issues/1691)

I would also like to discuss if we can't just use 'menlo' as the default font for plugdata to improve compatibility in general, not only for the vanilla theme... so

- [ ] make menlo the default font for plugdata (old discussion in https://github.com/plugdata-team/plugdata/issues/1692)

Another issue with font is iemguis, who should have a hardcoded font instead of loading the font from the theme, and it should really be those available in the original Vanilla distribution. If matching the font to the one PlugData uses is important, that's another reason to set 'menlo' as the default one.

- [ ] make labels from iemguis to have a hardcoded font (old discussion in https://github.com/plugdata-team/plugdata/issues/1671)

For last, plugdata doesn't recall the font size saved with the patch, but it should

- [ ] Make PlugData load font size according to the patch (old discussion in https://github.com/plugdata-team/plugdata/issues/1663)

**Comment by timothyschoen** [comment]
> A theme named 'vanilla' instead of classic

While this is possible, the theming name change would be difficult because people's settings already assume the theme is named "classic", so it would likely duplicate the theme. Since it's just a naming issue, I'd rather not touch it personally.

> make menlo the default font for plugdata

That won't happen, since the Inter font is an essential part of plugdata's visual identity. It's also much easier on the eyes as a font, and generally considered one of the best UI fonts out there. Plus: at this point that would make all existing plugdata patches look bad, which would be unacceptable. There's simply too much work out there made for plugdata specifically, that assumes the Inter font.

I do want to add a "font scale" option to allow a custom font choice to be scaled up/down, so that you can prevent text being much to small/large when picking a custom font. This is one of the biggest issues with using a font other than Inter right now.

> make the font theme set text in a patch

You're saying the font should be part of the theme instead of a global option right? I agree, that would indeed be better. Combined with a "font scale" option, it would allow Menlo to be the default for the classic/vanilla theme at least

> make labels from iemguis to have a hardcoded font 

I think the most sensible behaviour would be to have Menlo replaced with whatever the current active font in plugdata is, and still allow Helvetica and Times to be set. I see this doesn't work yet, so I should look into it for the next version. If we get per-theme fonts, that would make it use Menlo for the classic/vanilla theme anyway

> Make PlugData load font size according to the patch

I would like to do this, but it would be a big overhaul to how text rendering works in plugdata. I'll get to this at some point, but it won't be included in the upcoming release.

**Comment by porres** [comment]
> That won't happen, since the Inter font is an essential part of plugdata's visual identity.

I understand the font issue, but then we have a bigger problem with making patches compatible between PlugData and Vanilla Pd, and that's clearly reflected in the help files for all the objects. What could we do to address that?

> You're saying the font should be part of the theme instead of a global option right?

I meant that the font should affect the patch text, which I see it already does, so I don't know what happened :) 

The thing is I don't see a menlo font or dejavu sans mono in the font options for some reason, I wanted to test if we could change it and solve the current conflicts in a Vanilla theme.

> I think the most sensible behaviour would be to have Menlo replaced with whatever the current active font in plugdata is, and still allow Helvetica and Times to be set. 

seems like a nice compromise

**Comment by porres** [comment]
how crazy would it be to have per patch sttings with fonts and stuff? :)
